apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ynfh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ynfh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ynfh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ynfh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ynfh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ijht-tenant/rhtap-demo-app/hacbs-test-project-ynfh@sha256:f75a6d34eba85607cba48ab2146414546241fa6ed154b9cd9bc9bd2ef89bae32
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
