apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ynfh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ijht-tenant/rhtap-demo-app/hacbs-test-project-ynfh@sha256:7d1a720aa841e1808f870f4b2d8bf665a3420c941d0a5eeaa624a9556d22a922
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
